stages:
- name: Publish & Build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./AuthenticationService.WebApi/Dockerfile
      buildContext: .
      tag: authenticationservice:latest
      pushRemote: true
      registry: 192.168.1.164:9083
timeout: 60
notification: {}
