stages:
- name: demo
  steps:
  - publishImageConfig:
      dockerfilePath: ./AuthenticationService.WebApi/Dockerfile
      buildContext: .
      tag: AuthenticationService:latest
      pushRemote: true
      registry: 127.0.0.1:34066
    when:
      event:
        include:
        - push
  when:
    event:
      include:
      - push
timeout: 60
branch: {}
notification: {}
