stages:
- name: Publish & Build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./AuthenticationService.WebApi/Dockerfile
      buildContext: .
      tag: authenticationservice:latest
      pushRemote: true
      registry: localhost:5000
    when:
      event: {}
  when:
    event:
      include:
      - push
timeout: 60
branch: {}
notification: {}
