stages:
- name: demo
  steps:
  - publishImageConfig:
      dockerfilePath: ./AuthenticationService.WebApi/Dockerfile
      buildContext: .
      tag: AuthenticationService
  when:
    event:
      include:
      - push
timeout: 60
notification: {}
