stages:
- name: Publish & Build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./AuthenticationService.WebApi/Dockerfile
      buildContext: .
      tag: authenticationservice:latest
      registry: 127.0.0.1:34066
    when:
      event: {}
  when:
    event:
      include:
      - push
timeout: 60
branch: {}
notification: {}
